name: Build Arch PKG
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Package
        uses: hapakaien/archlinux-package-action@v2
        with:
          path: 'mesa-git'
          namcap: false

      - name: Publish Package Artifact
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            mesa-git/mesa-git-*.pkg.tar.zst
